version: "3.3"
services:
  server1-becd9691-b958-47c3-9ac3-688ca48fb6d6:
    image: kauri
    command: ['bls','10','6','10','100','25','1000']
    hostname: server1
    cap_add:
      - NET_ADMIN
    labels:
      becd9691-b958-47c3-9ac3-688ca48fb6d6: "true"
    deploy:
      replicas: 11
      endpoint_mode: dnsrr
    environment:
      KAURI_UUID: 'becd9691-b958-47c3-9ac3-688ca48fb6d6'
    networks:
      - KauriNet

  server-becd9691-b958-47c3-9ac3-688ca48fb6d6:
    image: kauri
    command: ['bls','10','6','10','100','25','1000']
    hostname: server
    cap_add:
      - NET_ADMIN
    labels:
      becd9691-b958-47c3-9ac3-688ca48fb6d6: "true"
    deploy:
      replicas: 89
      endpoint_mode: dnsrr
    environment:
      KAURI_UUID: 'becd9691-b958-47c3-9ac3-688ca48fb6d6'
    networks:
      - KauriNet

networks:
  KauriNet:
    external:
      name: kauri_network
  outside:
    driver: overlay
